site_name: Package Name
repo_url: https://github.com/USERNAME/REPO
repo_name: Name on the tab
site_dir: public
site_description: "Documentation for the package"
site_author: "@Jtachan"

nav:
  - Home: 'index.md'

theme:
  name: material
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.sections
    - search.suggest
    - search.highlight
    - toc.follow

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:  # https://mkdocstrings.github.io/python/usage/
          options:
            # General options
            show_bases: false
            show_source: false
            # Headings
            heading_level: 1
            parameter_headings: true
            show_root_heading: true
            show_root_full_path: true
            show_root_members_full_path: false
            show_category_heading: false
            # Members
            inherited_members: true
            members_order: source
            filters:
              - "!^_.*$"
            group_by_category: true
            show_submodules: true
            # Docstrings
            docstring_style: numpy
            docstring_section_style: table
            merge_init_into_class: true
            # Signatures
            annotations_path: source
            line_length: 88
            modernize_annotations: true
            overloads_only: true
            show_signature: true
            show_signature_annotations: true
            separate_signature: true
            show_overloads: true

markdown_extensions:
  - admonition  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admonition#supported-types
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: true
